# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea82a039f7118e1c3b81b2185a90cfd0ad276522b95f28e81b9d2f09ea07f8e288cd0d45a4fe1ae4533c326f4713216362412235b749f64af0a113d4e629fab8

test:
  secret_key_base: bcf7cc2bfe0106aba5b2218fcc9d748ca28fe62e15e0131f88db80a1a09ca2546d8ed5986ba737638d78e5bbb0d3d26de7e354f4dfb8347f1f9d34b0ef9f52bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
